### ISSUE TITLE
Where is the example?

### ISSUE THREAD

**Issue by ghubLIANG** [Asad-Ismail/Grounding-Dino-FineTuning#7]
hi, where is "multimodal-data/annotation/annotation.csv" ?

**Comment by Asad-Ismail** [comment]
Hi thank you for your interest I should be able to upload an example in next 2 days. Please note a better example dataset is being created which will be more useful but will take some time few weeks

**Comment by cristinayyds** [comment]
Hi, I am very expected to see the uploaded files

**Comment by Asad-Ismail** [comment]
Hello please see the example of annotation here https://github.com/Asad-Ismail/Grounding-Dino-FineTuning/tree/main/multimodal-data/annotation, you can follow the same annotation format to custom train the model on  your dataset,  I cannot upload the images due to privacy reasons, but I am working on open dataset to be added soon(approx 1 week timeline) you can also follow this enhancement to keep upto date https://github.com/Asad-Ismail/Grounding-Dino-FineTuning/issues/8 on this enhancement
